version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: change_logomark
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    volumes:
      - ./docker/data:/var/lib/mysql
